service: saddle-oz-defender-serverless
configValidationMode: error
useDotenv: true
frameworkVersion: '3'

# secrets:
#   # optional - global secrets are not affected by stackName changes
#   global:
#     foo: ${self:custom.config.secrets.foo}
#     hello: ${self:custom.config.secrets.hello}
#   # optional - stack secrets (formatted as <stackname>_<secretkey>)
#   mystack:
#     test: ${self:custom.config.secrets.test}

provider:
  name: defender
  stage: ${opt:stage, 'dev'}
  stackName: 'mystack'
  # SSOT: use this template as a single source of truth. 
  # This will delete Defender resources (with the exception of Relayers) not found in this template upon deployment.
  ssot: false

defender:
  key: "${env:TEAM_API_KEY}"
  secret: "${env:TEAM_API_SECRET}"

functions:
  root-gauge-factory-automation:
    name: 'Bridges root gauge factory transmit emission to side chains'
    path: './dist/root-gauge-factory-automation'
    relayer: ${self:resources.Resources.relayers.root-gauge-factory-automation-relayer}
    trigger:
      type: "schedule"
      cron: "0 0 * * THU"
    paused: false

  ve-sdl-oracle-automation:
    name: 'Bridges ve-sdl balance info to side chains using RootOracle'
    path: './dist/ve-sdl-oracle-automation'
    relayer: ${self:resources.Resources.relayers.root-gauge-factory-automation-relayer}
    trigger:
      type: "schedule"
      cron: "0 0 * * THU"
    paused: false

  arb-child-gauge-factory-automation:
    name: 'Calls mint on ChildGaugeFactory for all child gauges on Arbitrum'
    path: './dist/child-gauge-factory-automation'
    relayer: ${self:resources.Resources.relayers.child-gauge-factory-automation-relayer-arb}
    trigger:
      type: "schedule"
      cron: "0 20 * * THU"
    paused: false

  opt-child-gauge-factory-automation:
    name: 'Calls mint on ChildGaugeFactory for all child gauges on Optimism'
    path: './dist/child-gauge-factory-automation'
    relayer: ${self:resources.Resources.relayers.child-gauge-factory-automation-relayer-opt}
    trigger:
      type: "schedule"
      cron: "0 20 * * THU"
    paused: false

  example-task:
    name: 'Test function for debugging'
    path: './dist/example-task'
    relayer: ${self:resources.Resources.relayers.child-gauge-factory-automation-relayer-arb}
    trigger:
      type: "schedule"
      cron: "0 20 * * THU"
    paused: false


resources:
  Resources:
    policies:
      root-gauge-factory-automation-policy:
        gas-price-cap: 1000
        whitelist-receivers:
          - "0x19a5Ec09eE74f64573ac53f48A48616CE943C047"
          - "0x99Cb6c36816dE2131eF2626bb5dEF7E5cc8b9B14"
        eip1559-pricing: true
        private-transactions: false

      child-gauge-factory-automation-policy:
        gas-price-cap: 1000
        whitelist-receivers:
          - "0x19a5Ec09eE74f64573ac53f48A48616CE943C047"

        eip1559-pricing: true
        private-transactions: false

    relayers:
      root-gauge-factory-automation-relayer:
        name: "RootGaugeFactory automation relayer"
        network: "mainnet"
        min-balance: 1000
        policy: ${self:resources.Resources.policies.root-gauge-factory-automation-policy}
        api-keys:
          - key1

      child-gauge-factory-automation-relayer-arb:
        name: "ChildGaugeFactory automation relayer Arb"
        network: "arbitrum"
        min-balance: 1000
        policy: ${self:resources.Resources.policies.child-gauge-factory-automation-policy}
        api-keys:
          - key1

      child-gauge-factory-automation-relayer-opt:
        name: "ChildGaugeFactory automation relayer Opt"
        network: "optimism"
        min-balance: 1000
        policy: ${self:resources.Resources.policies.child-gauge-factory-automation-policy}
        api-keys:
          - key1

plugins:
  - defender-serverless


